### ISSUE TITLE
Local NVMe array not mounted correctly on nv-ai-02.srv.aau.dk

### ISSUE THREAD

**Issue by ThomasA** [aau-claaudia/aicloud#33]
The 30 TB local NVMe array is not mounted on /raid on nv-ai-02.srv.aau.dk like it is on nv-ai-01.srv.aau.dk and nv-ai-03.srv.aau.dk.

    nv-ai-02:~$ df -h /raid/
    Filesystem      Size  Used Avail Use% Mounted on
    /dev/md0        878G  682G  152G  82% /

vs.:

    nv-ai-01:~$ df -h /raid/
    Filesystem      Size  Used Avail Use% Mounted on
    /dev/md1         28T  790G   26T   3% /raid
    
    nv-ai-03:~$ df -h /raid/
    Filesystem      Size  Used Avail Use% Mounted on
    /dev/md1         28T  588G   26T   3% /raid

**Comment by fasmide** [comment]
👀

**Comment by ThomasA** [comment]
Closing this issue unfixed as the server has been retired.
